### ISSUE TITLE
Can't build on OGRE 2.x

### ISSUE THREAD

**Issue by TaaTT4** [OGRECave/meshmagick#5]
The [latest commit](https://github.com/OGRECave/meshmagick/commit/3ba94f5cb0016294b42c7a4fc96a0baca3312d7b) on ogre-next branch prevents MeshMagick from build with OGRE 2.x.

- Some `using` are missing (e.g. `v1::HardwareIndexBuffer`)
- `using` isn't probably enough by itself in every case because of ambiguous symbols (e.g. [here](https://github.com/OGRECave/meshmagick/blob/master/src/MmTootleTool.cpp#L340))
- Some `v1` namespace prefixes have been lost (e.g. [here](https://github.com/OGRECave/meshmagick/blob/master/src/MmTootleTool.cpp#L341))

**Comment by paroj** [comment]
should be fixed now
